##For configuration purposes, enter the samples in the SRR and Biosample headings following the yaml syntax
SRR:
  - SRR9951080
  - SRR9951081
  

Biosample:
  - SAMN12560275
  
##For STAR section, comment out/uncomment the variable depending on the 10x genomics version of your sample: Whitelist_file_v2: /data/lab/737K-august-2016.txt or Whitelist_file_v3: /data/lab/Homo_sapiens/3M-february-2018.txt
## For UMI_length the value is 12 for v3 10 for v2

STAR: 
  Whitelist: /data/lab/Homo_sapiens/3M-february-2018.txt
##Currently unimplemented: if v2, edit the rule 'STARsolo' directly   
#  UMI_length: 12
#  Overhang: 150
  
##Replace the paths below with your corresponding files 

Genome_dir: /data/lab/Homo_sapiens/genome
GTF_file: /data/lab/Homo_sapiens/genome/Homo_sapiens.GRCh38.79.gtf
Fasta_fa_file: /data/lab/Homo_sapiens/genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa
Fasta_index_file: /data/lab/Homo_sapiens/hg38_no_chr.fa.fai

Path2fastqs: ~/Snakemake/fastqs/
Path2samples: ~/Snakemake/fastqs/ind_bams/
Path2logs: ~/Snakemake/fastqs/logs/
Path2strelka: ~/Snakemake/fastqs/strelka/
Path2output: ~/Snakemake/fastqs/ind_bams/${i}_sample/
